---
language: node_js

compiler:
  - gcc

node_js:
  - "0.10"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - sudo g++ --version;
  - sudo apt-get update -qq;

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

deploy:
  provider: heroku
  strategy: api
  buildpack: https://github.com/tonycoco/heroku-buildpack-ember-cli.git
  api_key:
    secure: SdUfMZVRlmaZNST1rvzm7uX3g5zhGlaIL1DHKYB5QClfVg8V+MzQhe1jgTmAxBD2fWZklSOd8tNeLyiBrX+x6+bFY1lAFtZysKQdZwBq9DdNeCoT4u65xshuN2KvlcVtPwH88VvLKuSN7JwEqkBIVkntKIEEY3tG/4Yu1iuK/kE=
  app: liveband
